name: EPITA

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Tensorflow
        run: |
          wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.4.0.tar.gz
          sudo tar -C /usr/local -xzf libtensorflow-cpu-linux-x86_64-2.4.0.tar.gz
          sudo ldconfig
      - name: Install Other
        run: |
          sudo apt-get update -y -qq
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade pip
          pip install tensorflow
          sudo apt install cmake libcurl4-openssl-dev libflac-dev libasound-dev
      - name: Install deps
        run: |
          sudo apt-get update -y -qq
          sudo apt install cmake libcurl4-openssl-dev libflac-dev libasound-dev
      - name: Make the projet
        run: |
          make