name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update -y -qq
          sudo apt install libcurl4-openssl-dev cmake
      - name: Make the projet
        run: |
          cmake .
          make